Easier to read pack uwsgi vars
andreif/uwsgi-tools pull request #8
Opened 2018-05-24 21:59 UTC by tomdottom

NOTE: builds on work in #7 

This is some work I did whilst trying to debug another issue. It doesn't change the functionality.
But now we are able to reference uwsgi definitions documented at http://uwsgi-docs.readthedocs.io/en/latest/Protocol.html

From commit 5879abe0d2419d623682f630de3e12cc97f94779:

    Updates pack_uwsgi_vars
    
    Old packing of uwsgi vars seemed a little bit like magic and was hard to understand
    at least for mere mortals like myself.
    
    Created a pair of C Structures using definitions on uwsgi site and a helper function
    to convert to bytes.

2018-05-25 05:40 UTC, andreif commented
Thanks! Could you please fix linting errors?

2018-05-25 05:45 UTC, andreif commented
Also, please, rebase on master. GitHub stopped doing it automatically it seems.

2018-05-25 13:21 UTC, tomdottom commented
Rebased and ready to merge.

2018-05-25 13:34 UTC, tomdottom commented
:thinking: I'm not sure why the coverage test stalled

2018-05-29 10:21 UTC, andreif requested changes

2018-05-29 10:21 UTC, andreif commented on uwsgi_tools/uwsgi_structs.py
> +        struct uwsgi_packet_header {
indent issue

2018-05-29 10:21 UTC, andreif commented on .gitignore
> +.vscode
It's tempting but I think the best way is to put all of this in `~/.gitignore_global`. The old lines could also go there but since they are already committed... Local `.gitignore` should probably have project-related entries only.

2018-05-29 10:21 UTC, andreif commented on tests/test_uwsgi_structs.py
> +
The other class has no empty line.

2018-05-29 10:21 UTC, andreif commented on uwsgi_tools/uwsgi_structs.py
> +    _pack_ = 1
Missing empty line

2018-05-29 10:21 UTC, andreif commented on tests/test_uwsgi_structs.py
> +"""
This is not necessary since it's already in docstring of `uwsgi_structs.py`

2018-05-29 10:21 UTC, andreif commented on uwsgi_tools/uwsgi_structs.py
> +    };
If the semicolon necessary, then it should also be in the other class. Otherwise we can remove it

2018-05-29 15:17 UTC, tomdottom commented on .gitignore
> +.vscode
Most of the excludes were from the autogenerated github python .gitignore file.
However, I didn't realise you could do `git config --global core.excludesfile '~/.gitignore`

You learn something every day. Change to .gitignore reverted.

We might want to include *.pyc and __pycache__

2018-05-29 15:18 UTC, tomdottom commented
Changes implemented

2018-05-30 06:20 UTC, andreif approved these changes

2018-05-30 06:21 UTC, merged

2018-05-30 06:21 UTC, andreif commented
Awesome, thanks!